#!/usr/local/bin/python3.7

"""
This script plots amplitude field slices, using data generated by Ultraino simulations.

Euan Freeman (University of Glasgow)
Alexander Ng (University of Glasgow)
"""

import sys
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import griddata
import mpld3


def Plotcalculate(filename, x, y, z):
    # Read from the file. Expected format: `X,Y,Z,Amplitude`
    _x, _y, _z, _amplitude = np.loadtxt(filename, delimiter=",").T

    # Take the other values for the given fixed axis value
    x_axis = []
    y_axis = []
    z_axis = []
    ap = []

    # Update our internal representation of the data
    for i in range(len(_amplitude)):
        x_axis += [_x[i]]
        y_axis += [_y[i]]
        z_axis += [_z[i]]
        ap += [_amplitude[i]]

    i = 0;
    while i < len(_amplitude):
        if x_axis[i] == x:
            if y_axis[i] == y:
                if z_axis[i] == z:
                    return ap[i]
                else:
                    i += 1
                    continue
            else:
                i +=1
                continue
        else:
            i +=1
            continue


    # Convert from
    #
    #
    # # Python arrays to Numpy arrays
    # x = np.array(x_axis)
    # y = np.array(y_axis)
    # # amplitude = np.array(amplitude)
    # # arr = np.array(x_axis,y_axis)
    # print(x)


if __name__ == "__main__":
    Plotcalculate('A-8x16.csv', -0.08, 0.11, -0.08)
